import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card/index.js'
import Link from 'next/link'



export default function Home() {

  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className={styles.NavBarBackground}>
      <div className={styles.navBar}>
          <div><Link href="about">About</Link></div>
          <div><Link href="/">Home</Link></div>
      </div>
      </div>
      <div className={styles.Finance}>
        <div className={styles.Frame1}>
          <div className={styles.pic1}>
            <div className={styles.text1}>
            </div>
          </div>
        </div>
      </div>
        <div className={styles.container}>
        {
          information && information.map((info, index) => {
            if (info.department.toLowerCase() === "business") {
              return (
                <Card key={index} degree={info.degree} colour="red" font="10px" />
              )
        }
          })
        }
        </div>
        {
          information && information.map((info, index) => {
            if (info.department.toLowerCase() === "computing") {
              return (
                <Card key={index} degree={info.degree} colour="blue" font="50px" />
              )

            }


          })
        }

      </main>
    </>
  )
}
